import os
from langchain.document_loaders.pdf import PyPDFDirectoryLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_experimental.text_splitter import SemanticChunker
from langchain.schema.document import Document
from langchain_openai import OpenAIEmbeddings
from dotenv import load_dotenv
from langchain.vectorstores.chroma import Chroma